name: tagpr
on:
  push:
    branches: ["main"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Songmu/tagpr@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: haya14busa/action-update-semver@v1
        if: "steps.tagpr.outputs.tag != ''"
        with:
          tag: ${{ steps.tagpr.outputs.tag }}
