# .github/workflows/tagpr.yml

name: tagpr
on:
  push:
    branches:
      - main

jobs:
  tagpr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.RELEASE_TOKEN}}
      - id: run-tagpr
        name: Run tagpr
        uses: Songmu/tagpr@main
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
